### ISSUE TITLE
Consider building as AnyCPU

### ISSUE THREAD

**Issue by nohwnd** [isindicic/DependencyWalker.Net#5]
Thanks for your tool. I have been using it occasionally for years. 

The main executable is built as x86, which prevents any x64 dll or exe to be loaded, because of BadFormat exception:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/5735905/179212231-0df512db-e372-4702-95c1-5ce19f2d5221.png">

A solution to this would be to produce build the exe as AnyCPU and let it select the correct architecture, most likely x64, but maybe it would work on arm64 windows as well. You just need to change your ConfigurationManager settings to AnyCPU rather than x86. Then it can load both x86 and x64 dlls in the same session (on x64 device).

Would you accept a PR for this? I would also have to modernize your sln probably, I don't have the build environment. Is upgrading to VS2022 okay?

As a workaround: It is possible to patch your executable by running (from developer command line): `corflags DependencyWalker.exe /32BITREQ- /32BITPREF-` to make it not prefer 32 bit.

**Comment by nohwnd** [comment]
Repro for the error above: 

```csproj
<!-- file ClassLibrary1.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>

	<!-- force x64 -->
	<RuntimeIdentifier>win10-x64</RuntimeIdentifier>

  </PropertyGroup>

</Project>

```

```cs
// file Class1.cs
using System;

namespace ClassLibrary1
{
    public class Class1
    {

    }
}

```

**Comment by isindicic** [comment]
New version is now built for AnyCPU. 
Please try it and let me know if this solve your problems

**Comment by nohwnd** [comment]
@isindicic  I still see the exe in the latest zip as being built for x86. And the process runs as 32-bit. 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/5735905/185552880-9613c5d5-e987-4bac-a249-0f695948c801.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/5735905/185552628-c15bd0c6-9f8c-43f0-b442-b5813ad22b93.png">


I've made a PR using VS2022 and reverted all the irrelevant parts in the sln, there were not many so I am hopeful it will still be able to build. I am keeping my PR open for your edits, feel free to push any additional changes into it.

Thanks.

**Comment by Nikita-T86** [comment]
What I found is that DependencyWalker.Cli.exe now accepts x64 assemblies, but GUI version DependencyWalker.exe still doesn't work with x64.
